visitors.config:
  type: config_object
  label: 'Visitors Settings'
  mapping:
    chart_height:
      type: integer
      label: 'chart height'
    chart_width:
      type: integer
      label: 'chart width'
    flush_log_timer:
      label: 'log retention time'
      type: integer
    items_per_page:
      type: integer
      label: 'items per page'
    show_last_registered_user:
      type: boolean
      label: 'show last registered user'
    show_published_nodes:
      type: boolean
      label: 'show published nodes'
    show_registered_users_count:
      type: boolean
      label: 'show count of registered users'
    show_since_date:
      type: boolean
      label: 'show registration date'
    show_total_visitors:
      type: boolean
      label: 'show total visitors'
    show_unique_visitor:
      type: boolean
      label: 'show unique visitors'
    show_user_ip:
      type: boolean
      label: 'show user ip'
    start_count_total_visitors:
      type: integer
      label: 'initial total visitors count'
    theme:
      type: string
      label: 'visitors active theme'
    disable_tracking:
      type: boolean
      label: 'disable tracking'
    status_codes_disabled:
      type: sequence
      label: 'Status codes disabled'
      sequence:
        type: string
        label: 'Status code'
    domain_mode:
      type: integer
      label: 'Domain mode'
    track:
      type: mapping
      label: 'Links and downloads'
      mapping:
        userid:
          type: boolean
          label: 'Track User ID'

    codesnippet:
      type: mapping
      label: 'Custom code snippets'
      mapping:
        before:
          type: string
          label: 'Code snippet (before)'
        after:
          type: string
          label: 'Code snippet (after)'

    privacy:
      type: mapping
      label: 'Privacy'
      mapping:
        disablecookies:
          type: boolean
          label: 'Disable cookies'
    visibility:
      type: mapping
      label: 'Visibility'
      mapping:
        request_path_mode:
          type: integer
          label: 'Add tracking to specific pages'
        request_path_pages:
          type: string
          label: 'Pages by their paths'
        user_role_mode:
          type: integer
          label: 'Add tracking for specific roles'
        user_role_roles:
          type: sequence
          label: 'Roles'
          sequence:
            type: string
            label: 'Role'
        user_account_mode:
          type: integer
          label: 'Allow users to customize tracking on their account page'
        exclude_user1:
          type: boolean
          label: 'exclude user1'

block.settings.visitors_block:
  type: block_settings
  label: 'Visitors block configuration'
  mapping:
    show_last_registered_user:
      type: boolean
      label: 'show last registered user'
    show_published_nodes:
      type: boolean
      label: 'show published nodes'
    show_registered_users_count:
      type: boolean
      label: 'show count of registered users'
    show_since_date:
      type: boolean
      label: 'show registration date'
    show_total_visitors:
      type: boolean
      label: 'show total visitors'
    show_unique_visitor:
      type: boolean
      label: 'show unique visitors'
    show_user_ip:
      type: boolean
      label: 'show user ip'
